#!/bin/sh
set -eu

generate_admin_allowlist() {
    output_file="$1"
    mode="${ADMIN_SECURITY_MODE:-strict}"

    if [ "$mode" != "strict" ]; then
        echo "ERROR: only ADMIN_SECURITY_MODE=strict is supported in this release." >&2
        return 1
    fi

    output_dir=$(dirname "$output_file")
    mkdir -p "$output_dir"
    temp_file="${output_file}.tmp.$$"
    trap 'rm -f "$temp_file"' EXIT HUP INT TERM

    {
        echo "# Generated at container startup from ADMIN_ALLOWED_IPS."
        echo "# Do not edit this file inside the container."
        echo "allow 127.0.0.1;"
        echo "allow ::1;"
    } > "$temp_file"

    raw_ips="${ADMIN_ALLOWED_IPS:-}"
    if [ -n "$raw_ips" ]; then
        old_ifs=$IFS
        IFS=','
        set -- $raw_ips
        IFS=$old_ifs

        for raw_ip in "$@"; do
            ip=$(printf '%s' "$raw_ip" | tr -d '[:space:]')

            if [ -z "$ip" ]; then
                echo "ERROR: ADMIN_ALLOWED_IPS contains an empty entry." >&2
                return 1
            fi

            case "$ip" in
                *[!0-9A-Fa-f:.]*)
                    echo "ERROR: invalid IP in ADMIN_ALLOWED_IPS: $ip" >&2
                    return 1
                    ;;
            esac

            case "$ip" in
                *.*|*:*) ;;
                *)
                    echo "ERROR: invalid IP in ADMIN_ALLOWED_IPS: $ip" >&2
                    return 1
                    ;;
            esac

            rule="allow $ip;"
            if ! grep -Fqx "$rule" "$temp_file"; then
                printf '%s\n' "$rule" >> "$temp_file"
            fi
        done
    fi

    echo "deny all;" >> "$temp_file"
    chmod 0644 "$temp_file"
    mv "$temp_file" "$output_file"
    trap - EXIT HUP INT TERM

    echo "Generated strict Admin allowlist with ADMIN_ALLOWED_IPS." >&2
}

if [ "${1:-}" = "--generate-only" ]; then
    if [ "$#" -ne 2 ]; then
        echo "Usage: $0 --generate-only OUTPUT_FILE" >&2
        exit 2
    fi
    generate_admin_allowlist "$2"
    exit 0
fi

generate_admin_allowlist /etc/nginx/admin-allowlist.conf
exec /docker-entrypoint.sh "$@"
